version: "3"
services:
  repository-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    environment:
      - GITHUB_API_URL=https://api.github.com/search
